// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFkkt-7WlBMwhd4eTZGF0JZRoBcjA8FK8',
    appId: '1:716404099932:web:2aed40d4bf1f35856e8f99',
    messagingSenderId: '716404099932',
    projectId: 'revol-734dd',
    authDomain: 'revol-734dd.firebaseapp.com',
    databaseURL: 'https://revol-734dd-default-rtdb.firebaseio.com',
    storageBucket: 'revol-734dd.firebasestorage.app',
    measurementId: 'G-E6EMMPJMW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCayQOM38Y-JfzFDRCRvWw0hDobVXox0tM',
    appId: '1:716404099932:android:e9047db6c50d868b6e8f99',
    messagingSenderId: '716404099932',
    projectId: 'revol-734dd',
    databaseURL: 'https://revol-734dd-default-rtdb.firebaseio.com',
    storageBucket: 'revol-734dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB04-ChSZIFUIL8jBcjkePkGkj34cZRDmQ',
    appId: '1:716404099932:ios:8323afe432c16aeb6e8f99',
    messagingSenderId: '716404099932',
    projectId: 'revol-734dd',
    databaseURL: 'https://revol-734dd-default-rtdb.firebaseio.com',
    storageBucket: 'revol-734dd.firebasestorage.app',
    androidClientId: '716404099932-8f5to3eg751v0abi7kn6b9eg9h6vfg3e.apps.googleusercontent.com',
    iosClientId: '716404099932-qk5ol2tt6sg39spnk8knvgshd4n7p8pr.apps.googleusercontent.com',
    iosBundleId: 'protal.revollims.com',
  );
}
